# Conclusion

This project aims to explore time/region trend of natural disasters, and its related influences. One of the limitations of our projects is that we study different disasters independently. In reality, there maybe interactions of hazards that may cause further impacts have further implications. For this project, we were not able to cover this topic in details. Also, when studying the damages caused by disasters, the data is very incomplete, containing high proportion of missing values. The results drawn from the non-missing data might be biased, and we fail to link the damages more closely with the previous study of the occurrence pattern which is also something that we could continue study for this project. Another aspect we could further study as mentioned above is the potential correlations between attributes. One of the lessons we learned from doing this project is that the amount of data, and potential aspects we could explore in the data can be overwhelmingly vast, and it's crucial to structure the analyses, organize schedule and balance efforts on priorities.